include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_constructors: ignore
    prefer_final_fields: ignore

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
