/// Comprehensive Nigerian Geographic Directory
/// Contains all 36 States + Federal Capital Territory (Abuja) and their respective Delivery Zones / LGAs / Cities.
class NigeriaLocations {
  static const List<String> states = [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'FCT - Abuja',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
  ];

  static const Map<String, List<String>> stateCities = {
    'Abia': [
      'Aba North',
      'Aba South',
      'Umuahia North',
      'Umuahia South',
      'Osisioma',
      'Ohafia',
      'Arochukwu',
      'Ikwuano',
      'Isiala Ngwa',
      'Ugwunagbo',
    ],
    'Adamawa': [
      'Yola North (Jimeta)',
      'Yola South',
      'Mubi North',
      'Mubi South',
      'Numan',
      'Girei',
      'Michika',
      'Fufore',
      'Ganye',
    ],
    'Akwa Ibom': [
      'Uyo Urban',
      'Eket',
      'Ikot Ekpene',
      'Oron',
      'Abak',
      'Ikot Abasi',
      'Itu',
      'Uruan',
      'Ibiono Ibom',
      'Etinan',
    ],
    'Anambra': [
      'Awka South',
      'Awka North',
      'Onitsha North',
      'Onitsha South',
      'Nnewi North',
      'Nnewi South',
      'Ogbaru',
      'Idemili North (Ogidi)',
      'Idemili South',
      'Aguata (Ekwulobia)',
      'Ihiala',
    ],
    'Bauchi': [
      'Bauchi Metropolis',
      'Azare (Katagum)',
      'Misau',
      'Jama\'are',
      'Ningi',
      'Tafawa Balewa',
      'Dass',
      'Alkaleri',
    ],
    'Bayelsa': [
      'Yenagoa Central',
      'Brass',
      'Nembe',
      'Ogbia',
      'Sagbama',
      'Southern Ijaw',
      'Ekeremor',
      'Kolokuma/Opokuma',
    ],
    'Benue': [
      'Makurdi',
      'Gboko',
      'Otukpo',
      'Katsina-Ala',
      'Vandeikya',
      'Gwer East',
      'Ukum',
      'Ogbadibo',
    ],
    'Borno': [
      'Maiduguri (MMC)',
      'Jere',
      'Biu',
      'Bama',
      'Monguno',
      'Konduga',
      'Gwoza',
      'Hawul',
    ],
    'Cross River': [
      'Calabar Municipal',
      'Calabar South',
      'Ikom',
      'Ogoja',
      'Obudu',
      'Akamkpa',
      'Yakurr (Ugep)',
      'Bekwarra',
    ],
    'Delta': [
      'Asaba (Oshimili South)',
      'Warri South',
      'Warri North',
      'Warri South-West',
      'Uvwie (Effurun)',
      'Ughelli North',
      'Ughelli South',
      'Sapele',
      'Ika North-East (Agbor)',
      'Okpe',
    ],
    'Ebonyi': [
      'Abakaliki',
      'Afikpo North',
      'Afikpo South',
      'Ezza North',
      'Ezza South',
      'Ishielu',
      'Ohaozara',
      'Ikwo',
    ],
    'Edo': [
      'Benin City (Oredo)',
      'Ikpoba-Okha',
      'Egor',
      'Auchi (Etsako West)',
      'Ekpoma (Esan West)',
      'Uromi (Esan North-East)',
      'Ovia North-East',
      'Uhunmwonde',
    ],
    'Ekiti': [
      'Ado-Ekiti',
      'Ikere-Ekiti',
      'Ijero-Ekiti',
      'Oye-Ekiti',
      'Ise/Orun',
      'Gbonyin',
      'Efon',
      'Ikole-Ekiti',
    ],
    'Enugu': [
      'Enugu North',
      'Enugu South',
      'Enugu East',
      'Nsukka',
      'Agbani (Nkanu West)',
      'Udi',
      'Oji River',
      'Awgu',
      'Igbo-Eze North',
    ],
    'FCT - Abuja': [
      'Wuse 2',
      'Wuse Zone 1 - 7',
      'Maitama',
      'Garki I & II',
      'Central Business District (CBD)',
      'Gwarinpa Estate',
      'Jabi & Utako',
      'Asokoro',
      'Guzape & Apo',
      'Kubwa',
      'Lugbe (Airport Road)',
      'Bwari',
      'Gwagwalada',
      'Kuje',
      'Karu & Nyanya',
      'Dawaki & Katampe',
      'Lokogoma & Galadimawa',
      'Life Camp & Kado',
    ],
    'Gombe': [
      'Gombe Metropolis',
      'Kaltungo',
      'Billiri',
      'Dukku',
      'Yamaltu/Deba',
      'Akko',
      'Funakaye (Bajoga)',
    ],
    'Imo': [
      'Owerri Municipal',
      'Owerri North',
      'Owerri West',
      'Orlu',
      'Okigwe',
      'Mbaise (Aboh/Ahiazu)',
      'Oguta',
      'Mbaitoli',
      'Ikeduru',
    ],
    'Jigawa': [
      'Dutse',
      'Hadejia',
      'Gumel',
      'Kazaure',
      'Ringim',
      'Birnin Kudu',
      'Babura',
      'Jahun',
    ],
    'Kaduna': [
      'Kaduna North',
      'Kaduna South',
      'Chikun (Barnawa / Sabo)',
      'Igabi (Rigasa)',
      'Zaria City',
      'Sabon Gari (Zaria)',
      'Kafanchan (Jema\'a)',
      'Kudan',
      'Soba',
    ],
    'Kano': [
      'Kano Municipal',
      'Fagge',
      'Dala',
      'Gwale',
      'Nassarawa',
      'Tarauni',
      'Kumbotso',
      'Ungogo',
      'Bichi',
      'Wudil',
      'Rano',
    ],
    'Katsina': [
      'Katsina Metropolis',
      'Daura',
      'Funtua',
      'Malumfashi',
      'Kankia',
      'Dutsin-Ma',
      'Mani',
      'Jibia',
    ],
    'Kebbi': [
      'Birnin Kebbi',
      'Argungu',
      'Yauri',
      'Zuru',
      'Jega',
      'Gwandu',
      'Bagudo',
      'Dandi',
    ],
    'Kogi': [
      'Lokoja',
      'Okene',
      'Kabba/Bunu',
      'Anyigba (Dekina)',
      'Idah',
      'Ankpa',
      'Ajaokuta',
      'Adavi',
    ],
    'Kwara': [
      'Ilorin South',
      'Ilorin West',
      'Ilorin East',
      'Offa',
      'Omu-Aran (Irepodun)',
      'Jebba (Moro)',
      'Edu (Lafiagi)',
      'Kaiama',
    ],
    'Lagos': [
      'Ikeja (GRA / Allen / Alausa)',
      'Lekki Phase 1 & 2',
      'Victoria Island (VI)',
      'Ikoyi',
      'Ajah & Sangotedo',
      'Chevron & Osapa London',
      'Yaba & Akoka',
      'Surulere',
      'Maryland & Anthony',
      'Magodo Phase 1 & 2',
      'Omole Phase 1 & 2',
      'Gbagada',
      'Ogudu & Ojota',
      'Festac Town & Amuwo Odofin',
      'Ikorodu Central',
      'Agege & Ogba',
      'Alimosho (Egbeda / Igando / Iyana Ipaja)',
      'Oshodi & Isolo',
      'Apapa',
      'Epe',
      'Badagry',
    ],
    'Nasarawa': [
      'Lafia Metropolis',
      'Keffi',
      'Karu (Mararaba / Nyanya)',
      'Akwanga',
      'Nasarawa Town',
      'Doma',
      'Wamba',
      'Toto',
    ],
    'Niger': [
      'Minna (Chanchaga)',
      'Suleja',
      'Bida',
      'Kontagora',
      'Lapai',
      'Mokwa',
      'Shiroro',
      'Borgu (New Bussa)',
    ],
    'Ogun': [
      'Abeokuta South',
      'Abeokuta North',
      'Sagamu',
      'Ijebu Ode',
      'Ota (Ado-Odo/Ota)',
      'Mowe & Ibafo (Obafemi Owode)',
      'Ilaro (Yewa South)',
      'Iperu / Remo North',
    ],
    'Ondo': [
      'Akure South',
      'Akure North',
      'Ondo West (Ondo Town)',
      'Owo',
      'Ikare-Akoko',
      'Ore (Odigbo)',
      'Okitipupa',
      'Idanre',
    ],
    'Osun': [
      'Osogbo Central',
      'Olorunda',
      'Ile-Ife (Central / East)',
      'Ilesa East & West',
      'Ede North & South',
      'Ikirun (Ifelodun)',
      'Ejigbo',
      'Iwo',
    ],
    'Oyo': [
      'Ibadan North (Bodija / Agodi)',
      'Ibadan North-East',
      'Ibadan South-West (Ring Road / Oluyole)',
      'Ibadan North-West (Dugbe)',
      'Ibadan South-East',
      'Ogbomoso North & South',
      'Oyo East & West (Oyo Town)',
      'Iseyin',
      'Saki West',
      'Egbeda (Ibadan)',
    ],
    'Plateau': [
      'Jos North',
      'Jos South (Bukuru)',
      'Jos East',
      'Barkin Ladi',
      'Pankshin',
      'Shendam',
      'Mangu',
      'Langtang North',
    ],
    'Rivers': [
      'Port Harcourt City (Old GRA / Town)',
      'Obio-Akpor (New GRA / Rumuokoro / Rumuola)',
      'Trans-Amadi Industrial Layout',
      'Eleme',
      'Oyigbo',
      'Ikwerre',
      'Bonny Island',
      'Okrika',
      'Ahoada East',
      'Degema',
    ],
    'Sokoto': [
      'Sokoto North',
      'Sokoto South',
      'Wamakko',
      'Tambuwal',
      'Gwadabawa',
      'Illela',
      'Bodinga',
      'Goronyo',
    ],
    'Taraba': [
      'Jalingo Metropolis',
      'Wukari',
      'Bali',
      'Takum',
      'Gembu (Sardauna)',
      'Gashaka',
      'Ibi',
      'Zing',
    ],
    'Yobe': [
      'Damaturu',
      'Gashua (Bade)',
      'Potiskum',
      'Nguru',
      'Geidam',
      'Fika',
      'Buni Yadi (Gujba)',
    ],
    'Zamfara': [
      'Gusau Metropolis',
      'Kaura Namoda',
      'Talata Mafara',
      'Tsafe',
      'Anka',
      'Maru',
      'Bungudu',
      'Zurmi',
    ],
  };

  /// Returns the available cities / LGAs for a given state name.
  /// Handles standardizations such as "Abuja (FCT)", "Lagos State", etc.
  static List<String> getCitiesForState(String stateName) {
    final clean = stateName.trim();

    // Direct match
    if (stateCities.containsKey(clean)) {
      return stateCities[clean]!;
    }

    // Normalized matches
    for (final entry in stateCities.entries) {
      if (clean.toLowerCase().contains(entry.key.toLowerCase()) ||
          entry.key.toLowerCase().contains(clean.toLowerCase())) {
        return entry.value;
      }
    }

    // Default fallback
    return stateCities['FCT - Abuja']!;
  }
}
